doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            employee_id: Payroll\Shared\UUID\DoctrineType\EmployeeIdType
            department_id: Payroll\Shared\UUID\DoctrineType\DepartmentIdType
            report_id: Payroll\Shared\UUID\DoctrineType\ReportIdType

        schema_filter: ~(?<!_read_model)$~
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Salary:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Salary/Infrastructure/config'
                prefix: 'Payroll\Salary\Domain'
                alias: Salary
            Report:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Report/Infrastructure/config'
                prefix: 'Payroll\Report\Domain'
                alias: Report
            Employment:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Employment/Infrastructure/config'
                prefix: 'Payroll\Employment\Domain'
                alias: Employment
            Money:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Money/config'
                prefix: 'Money'
                alias: Money

when@test:
    doctrine:
        dbal:
            # url: 'sqlite:///:memory:'
            # "TEST_TOKEN" is typically set by ParaTest
            # dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
