framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus: ~

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             sync: 'sync://'

        routing:
            # === COMMANDS ===
            # Salary
            Payroll\Salary\Application\Command\CalculateReportSalaries: sync
            Payroll\Salary\Application\Command\CreateEmployeeSalary: sync
            Payroll\Salary\Application\Command\SetDepartmentBonus: sync
            # Report
            Payroll\Report\Application\Command\FinishReportProcessing: sync
            Payroll\Report\Application\Command\GenerateSalaryReport: async
            # Employment
            Payroll\Employment\Application\Command\CreateDepartment: sync
            Payroll\Employment\Application\Command\CreateEmployee: sync

            # === EVENTS ===
            # Salary
            Payroll\Salary\Domain\DepartmentBonusChanged: sync
            Payroll\Salary\Domain\EmployeeSalaryChanged: sync
            Payroll\Salary\Domain\ReportSalariesCalculated: sync
            Payroll\Salary\Domain\SalaryCalculated: sync
            # Report
            Payroll\Report\Domain\ReportCreated: sync
            Payroll\Report\Domain\ReportProcessingFinished: sync
            # Employment
            Payroll\Employment\Domain\DepartmentRegistered: sync
            Payroll\Employment\Domain\EmployeeRegistered: sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                async: 'in-memory://'
