# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../app/'
        exclude:
            - '../app/Kernel.php'
    Payroll\:
        resource: '../src/'

    Payroll\Employment\Domain\DepartmentRepository: '@Payroll\Employment\Infrastructure\Repository\DoctrineDepartmentRepository'
    Payroll\Employment\Domain\EmployeeRepository: '@Payroll\Employment\Infrastructure\Repository\DoctrineEmployeeRepository'
    Payroll\Salary\Domain\DepartmentRepository: '@Payroll\Salary\Infrastructure\Repository\DoctrineDepartmentRepository'
    Payroll\Salary\Domain\EmployeeRepository: '@Payroll\Salary\Infrastructure\Repository\DoctrineEmployeeRepository'
    Payroll\Report\Domain\ReportRepository: '@Payroll\Report\Infrastructure\Repository\DoctrineReportRepository'

    Payroll\Shared\CommonClock:
        arguments:
            $timezone: '%timezone%'
    Payroll\Shared\Clock: '@Payroll\Shared\CommonClock'

    Payroll\Shared\CQRS\MessengerCommandBus:
        arguments:
            $bus: '@command.bus'
    Payroll\Shared\CQRS\MessengerQueryBus:
        arguments:
            $bus: '@query.bus'
    Payroll\Shared\Event\MessengerDomainEventBus:
        arguments:
            $bus: '@event.bus'

    Payroll\Shared\CQRS\CommandBus: '@Payroll\Shared\CQRS\MessengerCommandBus'
    Payroll\Shared\CQRS\QueryBus: '@Payroll\Shared\CQRS\MessengerQueryBus'
    Payroll\Shared\Event\DomainEventBus: '@Payroll\Shared\Event\MessengerDomainEventBus'

when@test:
    services:
        Payroll\Shared\Clock: '@Payroll\Shared\FakeClock'
